apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-gateway-config
data:
  OWNER: "ecommerce"
  CASDOOR_URL: "https://apikv.com:8081"
  CONSUL_ADDR: "consul://consul-server.consul.svc.cluster.local:8501"
  CONSUL_CONFIG_PATH: "ecommerce/gateway/config.yaml"
  CONSUL_CONFIG_PREFIX: "ecommerce/gateway"
  CONSUL_SCHEME: "https"
  CONSUL_INSECURE_SKIP_VERIFY: "true"
  POLICIES_FILE_PATH: "./dynamic-config/policies/policies.csv"
  MODEL_FILE_PATH: "./dynamic-config/policies/model.conf"
  USE_TLS: "false"
  USE_HTTP3: "false"
  HTTP_PORT: "8080"
