apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-gateway-deploy
  labels:
    app: ecommerce-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-gateway
  template:
    metadata:
      name: ecommerce-gateway
      labels:
        app: ecommerce-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: ecommerce-gateway
          image: harbor.apikv.com:5443/ecommerce/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: ecommerce-gateway
            - name: SERVICE_VERSION
              value: v1
            - name: CONFIG_SOURCE_FILE
              value: /etc/ecommerce/config-source/gateway.yaml
          envFrom:
            - configMapRef:
                name: ecommerce-gateway-config
          volumeMounts:
            - name: config-source
              mountPath: /etc/ecommerce/config-source
              readOnly: true
      volumes:
        - name: config-source
          secret:
            secretName: ecommerce-config-source-prod
            defaultMode: 0400
      restartPolicy: Always
      
