// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/middleware/tracing/v1/tracing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tracing middleware config.
type Tracing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report endpoint url
	HttpEndpoint string `protobuf:"bytes,1,opt,name=http_endpoint,json=httpEndpoint,proto3" json:"http_endpoint,omitempty"`
	// sample ratio
	SampleRatio *float32 `protobuf:"fixed32,2,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	// report timeout
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// ssl
	Insecure      *bool        `protobuf:"varint,5,opt,name=insecure,proto3,oneof" json:"insecure,omitempty"`
	Tls           *Tracing_TLS `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_tracing_v1_tracing_proto_rawDescGZIP(), []int{0}
}

func (x *Tracing) GetHttpEndpoint() string {
	if x != nil {
		return x.HttpEndpoint
	}
	return ""
}

func (x *Tracing) GetSampleRatio() float32 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

func (x *Tracing) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Tracing) GetInsecure() bool {
	if x != nil && x.Insecure != nil {
		return *x.Insecure
	}
	return false
}

func (x *Tracing) GetTls() *Tracing_TLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Tracing_TLS struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enable             bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	CaPem              string                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,3,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Tracing_TLS) Reset() {
	*x = Tracing_TLS{}
	mi := &file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing_TLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing_TLS) ProtoMessage() {}

func (x *Tracing_TLS) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing_TLS.ProtoReflect.Descriptor instead.
func (*Tracing_TLS) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_tracing_v1_tracing_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Tracing_TLS) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Tracing_TLS) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *Tracing_TLS) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

var File_gateway_middleware_tracing_v1_tracing_proto protoreflect.FileDescriptor

const file_gateway_middleware_tracing_v1_tracing_proto_rawDesc = "" +
	"\n" +
	"+gateway/middleware/tracing/v1/tracing.proto\x12\x1dgateway.middleware.tracing.v1\x1a\x1egoogle/protobuf/duration.proto\"\xf0\x02\n" +
	"\aTracing\x12#\n" +
	"\rhttp_endpoint\x18\x01 \x01(\tR\fhttpEndpoint\x12&\n" +
	"\fsample_ratio\x18\x02 \x01(\x02H\x00R\vsampleRatio\x88\x01\x01\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\binsecure\x18\x05 \x01(\bH\x01R\binsecure\x88\x01\x01\x12<\n" +
	"\x03tls\x18\x06 \x01(\v2*.gateway.middleware.tracing.v1.Tracing.TLSR\x03tls\x1af\n" +
	"\x03TLS\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem\x120\n" +
	"\x14insecure_skip_verify\x18\x03 \x01(\bR\x12insecureSkipVerifyB\x0f\n" +
	"\r_sample_ratioB\v\n" +
	"\t_insecureBCZAgithub.com/go-kratos/gateway/api/gateway/middleware/tracing/v1;v1b\x06proto3"

var (
	file_gateway_middleware_tracing_v1_tracing_proto_rawDescOnce sync.Once
	file_gateway_middleware_tracing_v1_tracing_proto_rawDescData []byte
)

func file_gateway_middleware_tracing_v1_tracing_proto_rawDescGZIP() []byte {
	file_gateway_middleware_tracing_v1_tracing_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_tracing_v1_tracing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc), len(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc)))
	})
	return file_gateway_middleware_tracing_v1_tracing_proto_rawDescData
}

var file_gateway_middleware_tracing_v1_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_middleware_tracing_v1_tracing_proto_goTypes = []any{
	(*Tracing)(nil),             // 0: gateway.middleware.tracing.v1.Tracing
	(*Tracing_TLS)(nil),         // 1: gateway.middleware.tracing.v1.Tracing.TLS
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_gateway_middleware_tracing_v1_tracing_proto_depIdxs = []int32{
	2, // 0: gateway.middleware.tracing.v1.Tracing.timeout:type_name -> google.protobuf.Duration
	1, // 1: gateway.middleware.tracing.v1.Tracing.tls:type_name -> gateway.middleware.tracing.v1.Tracing.TLS
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_middleware_tracing_v1_tracing_proto_init() }
func file_gateway_middleware_tracing_v1_tracing_proto_init() {
	if File_gateway_middleware_tracing_v1_tracing_proto != nil {
		return
	}
	file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc), len(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_tracing_v1_tracing_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_tracing_v1_tracing_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_tracing_v1_tracing_proto_msgTypes,
	}.Build()
	File_gateway_middleware_tracing_v1_tracing_proto = out.File
	file_gateway_middleware_tracing_v1_tracing_proto_goTypes = nil
	file_gateway_middleware_tracing_v1_tracing_proto_depIdxs = nil
}
