// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: gateway/middleware/tracing/v1/tracing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tracing middleware config.
type Tracing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report endpoint url
	HttpEndpoint string `protobuf:"bytes,1,opt,name=http_endpoint,json=httpEndpoint,proto3" json:"http_endpoint,omitempty"`
	// sample ratio
	SampleRatio *float32 `protobuf:"fixed32,2,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	// report timeout
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// ssl
	Insecure      *bool `protobuf:"varint,5,opt,name=insecure,proto3,oneof" json:"insecure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_tracing_v1_tracing_proto_rawDescGZIP(), []int{0}
}

func (x *Tracing) GetHttpEndpoint() string {
	if x != nil {
		return x.HttpEndpoint
	}
	return ""
}

func (x *Tracing) GetSampleRatio() float32 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

func (x *Tracing) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Tracing) GetInsecure() bool {
	if x != nil && x.Insecure != nil {
		return *x.Insecure
	}
	return false
}

var File_gateway_middleware_tracing_v1_tracing_proto protoreflect.FileDescriptor

const file_gateway_middleware_tracing_v1_tracing_proto_rawDesc = "" +
	"\n" +
	"+gateway/middleware/tracing/v1/tracing.proto\x12\x1dgateway.middleware.tracing.v1\x1a\x1egoogle/protobuf/duration.proto\"\xca\x01\n" +
	"\aTracing\x12#\n" +
	"\rhttp_endpoint\x18\x01 \x01(\tR\fhttpEndpoint\x12&\n" +
	"\fsample_ratio\x18\x02 \x01(\x02H\x00R\vsampleRatio\x88\x01\x01\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\binsecure\x18\x05 \x01(\bH\x01R\binsecure\x88\x01\x01B\x0f\n" +
	"\r_sample_ratioB\v\n" +
	"\t_insecureBCZAgithub.com/go-kratos/gateway/api/gateway/middleware/tracing/v1;v1b\x06proto3"

var (
	file_gateway_middleware_tracing_v1_tracing_proto_rawDescOnce sync.Once
	file_gateway_middleware_tracing_v1_tracing_proto_rawDescData []byte
)

func file_gateway_middleware_tracing_v1_tracing_proto_rawDescGZIP() []byte {
	file_gateway_middleware_tracing_v1_tracing_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_tracing_v1_tracing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc), len(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc)))
	})
	return file_gateway_middleware_tracing_v1_tracing_proto_rawDescData
}

var file_gateway_middleware_tracing_v1_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_middleware_tracing_v1_tracing_proto_goTypes = []any{
	(*Tracing)(nil),             // 0: gateway.middleware.tracing.v1.Tracing
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_gateway_middleware_tracing_v1_tracing_proto_depIdxs = []int32{
	1, // 0: gateway.middleware.tracing.v1.Tracing.timeout:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_middleware_tracing_v1_tracing_proto_init() }
func file_gateway_middleware_tracing_v1_tracing_proto_init() {
	if File_gateway_middleware_tracing_v1_tracing_proto != nil {
		return
	}
	file_gateway_middleware_tracing_v1_tracing_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc), len(file_gateway_middleware_tracing_v1_tracing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_tracing_v1_tracing_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_tracing_v1_tracing_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_tracing_v1_tracing_proto_msgTypes,
	}.Build()
	File_gateway_middleware_tracing_v1_tracing_proto = out.File
	file_gateway_middleware_tracing_v1_tracing_proto_goTypes = nil
	file_gateway_middleware_tracing_v1_tracing_proto_depIdxs = nil
}
