// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: gateway/middleware/jwt/v1/jwt.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_gateway_middleware_jwt_v1_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_jwt_v1_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_jwt_v1_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Rule) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type RouterFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterFilter) Reset() {
	*x = RouterFilter{}
	mi := &file_gateway_middleware_jwt_v1_jwt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterFilter) ProtoMessage() {}

func (x *RouterFilter) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_jwt_v1_jwt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterFilter.ProtoReflect.Descriptor instead.
func (*RouterFilter) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_jwt_v1_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *RouterFilter) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_gateway_middleware_jwt_v1_jwt_proto protoreflect.FileDescriptor

const file_gateway_middleware_jwt_v1_jwt_proto_rawDesc = "" +
	"\n" +
	"#gateway/middleware/jwt/v1/jwt.proto\x12\x19gateway.middleware.jwt.v1\"4\n" +
	"\x04Rule\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods\"E\n" +
	"\fRouterFilter\x125\n" +
	"\x05rules\x18\x01 \x03(\v2\x1f.gateway.middleware.jwt.v1.RuleR\x05rulesB?Z=github.com/go-kratos/gateway/api/gateway/middleware/jwt/v1;v1b\x06proto3"

var (
	file_gateway_middleware_jwt_v1_jwt_proto_rawDescOnce sync.Once
	file_gateway_middleware_jwt_v1_jwt_proto_rawDescData []byte
)

func file_gateway_middleware_jwt_v1_jwt_proto_rawDescGZIP() []byte {
	file_gateway_middleware_jwt_v1_jwt_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_jwt_v1_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc), len(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc)))
	})
	return file_gateway_middleware_jwt_v1_jwt_proto_rawDescData
}

var file_gateway_middleware_jwt_v1_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_middleware_jwt_v1_jwt_proto_goTypes = []any{
	(*Rule)(nil),         // 0: gateway.middleware.jwt.v1.Rule
	(*RouterFilter)(nil), // 1: gateway.middleware.jwt.v1.RouterFilter
}
var file_gateway_middleware_jwt_v1_jwt_proto_depIdxs = []int32{
	0, // 0: gateway.middleware.jwt.v1.RouterFilter.rules:type_name -> gateway.middleware.jwt.v1.Rule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_middleware_jwt_v1_jwt_proto_init() }
func file_gateway_middleware_jwt_v1_jwt_proto_init() {
	if File_gateway_middleware_jwt_v1_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc), len(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_jwt_v1_jwt_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_jwt_v1_jwt_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_jwt_v1_jwt_proto_msgTypes,
	}.Build()
	File_gateway_middleware_jwt_v1_jwt_proto = out.File
	file_gateway_middleware_jwt_v1_jwt_proto_goTypes = nil
	file_gateway_middleware_jwt_v1_jwt_proto_depIdxs = nil
}
