// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/middleware/rewrite/v1/rewrite.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rewrite middleware config.
type HeadersPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           map[string]string      `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Add           map[string]string      `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersPolicy) Reset() {
	*x = HeadersPolicy{}
	mi := &file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersPolicy) ProtoMessage() {}

func (x *HeadersPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersPolicy.ProtoReflect.Descriptor instead.
func (*HeadersPolicy) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescGZIP(), []int{0}
}

func (x *HeadersPolicy) GetSet() map[string]string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *HeadersPolicy) GetAdd() map[string]string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *HeadersPolicy) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type Rewrite struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PathRewrite            *string                `protobuf:"bytes,1,opt,name=path_rewrite,json=pathRewrite,proto3,oneof" json:"path_rewrite,omitempty"`
	RequestHeadersRewrite  *HeadersPolicy         `protobuf:"bytes,2,opt,name=request_headers_rewrite,json=requestHeadersRewrite,proto3" json:"request_headers_rewrite,omitempty"`
	ResponseHeadersRewrite *HeadersPolicy         `protobuf:"bytes,3,opt,name=response_headers_rewrite,json=responseHeadersRewrite,proto3" json:"response_headers_rewrite,omitempty"`
	StripPrefix            *string                `protobuf:"bytes,4,opt,name=strip_prefix,json=stripPrefix,proto3,oneof" json:"strip_prefix,omitempty"`
	HostRewrite            *string                `protobuf:"bytes,5,opt,name=host_rewrite,json=hostRewrite,proto3,oneof" json:"host_rewrite,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Rewrite) Reset() {
	*x = Rewrite{}
	mi := &file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rewrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rewrite) ProtoMessage() {}

func (x *Rewrite) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rewrite.ProtoReflect.Descriptor instead.
func (*Rewrite) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescGZIP(), []int{1}
}

func (x *Rewrite) GetPathRewrite() string {
	if x != nil && x.PathRewrite != nil {
		return *x.PathRewrite
	}
	return ""
}

func (x *Rewrite) GetRequestHeadersRewrite() *HeadersPolicy {
	if x != nil {
		return x.RequestHeadersRewrite
	}
	return nil
}

func (x *Rewrite) GetResponseHeadersRewrite() *HeadersPolicy {
	if x != nil {
		return x.ResponseHeadersRewrite
	}
	return nil
}

func (x *Rewrite) GetStripPrefix() string {
	if x != nil && x.StripPrefix != nil {
		return *x.StripPrefix
	}
	return ""
}

func (x *Rewrite) GetHostRewrite() string {
	if x != nil && x.HostRewrite != nil {
		return *x.HostRewrite
	}
	return ""
}

var File_gateway_middleware_rewrite_v1_rewrite_proto protoreflect.FileDescriptor

const file_gateway_middleware_rewrite_v1_rewrite_proto_rawDesc = "" +
	"\n" +
	"+gateway/middleware/rewrite/v1/rewrite.proto\x12\x1dgateway.middleware.rewrite.v1\"\xa9\x02\n" +
	"\rHeadersPolicy\x12G\n" +
	"\x03set\x18\x01 \x03(\v25.gateway.middleware.rewrite.v1.HeadersPolicy.SetEntryR\x03set\x12G\n" +
	"\x03add\x18\x02 \x03(\v25.gateway.middleware.rewrite.v1.HeadersPolicy.AddEntryR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\x1a6\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bAddEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x03\n" +
	"\aRewrite\x12&\n" +
	"\fpath_rewrite\x18\x01 \x01(\tH\x00R\vpathRewrite\x88\x01\x01\x12d\n" +
	"\x17request_headers_rewrite\x18\x02 \x01(\v2,.gateway.middleware.rewrite.v1.HeadersPolicyR\x15requestHeadersRewrite\x12f\n" +
	"\x18response_headers_rewrite\x18\x03 \x01(\v2,.gateway.middleware.rewrite.v1.HeadersPolicyR\x16responseHeadersRewrite\x12&\n" +
	"\fstrip_prefix\x18\x04 \x01(\tH\x01R\vstripPrefix\x88\x01\x01\x12&\n" +
	"\fhost_rewrite\x18\x05 \x01(\tH\x02R\vhostRewrite\x88\x01\x01B\x0f\n" +
	"\r_path_rewriteB\x0f\n" +
	"\r_strip_prefixB\x0f\n" +
	"\r_host_rewriteB@Z>github.com/go-kratos/gateway/api/gateway/middleware/rewrite/v1b\x06proto3"

var (
	file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescOnce sync.Once
	file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescData []byte
)

func file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescGZIP() []byte {
	file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_rewrite_v1_rewrite_proto_rawDesc), len(file_gateway_middleware_rewrite_v1_rewrite_proto_rawDesc)))
	})
	return file_gateway_middleware_rewrite_v1_rewrite_proto_rawDescData
}

var file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_middleware_rewrite_v1_rewrite_proto_goTypes = []any{
	(*HeadersPolicy)(nil), // 0: gateway.middleware.rewrite.v1.HeadersPolicy
	(*Rewrite)(nil),       // 1: gateway.middleware.rewrite.v1.Rewrite
	nil,                   // 2: gateway.middleware.rewrite.v1.HeadersPolicy.SetEntry
	nil,                   // 3: gateway.middleware.rewrite.v1.HeadersPolicy.AddEntry
}
var file_gateway_middleware_rewrite_v1_rewrite_proto_depIdxs = []int32{
	2, // 0: gateway.middleware.rewrite.v1.HeadersPolicy.set:type_name -> gateway.middleware.rewrite.v1.HeadersPolicy.SetEntry
	3, // 1: gateway.middleware.rewrite.v1.HeadersPolicy.add:type_name -> gateway.middleware.rewrite.v1.HeadersPolicy.AddEntry
	0, // 2: gateway.middleware.rewrite.v1.Rewrite.request_headers_rewrite:type_name -> gateway.middleware.rewrite.v1.HeadersPolicy
	0, // 3: gateway.middleware.rewrite.v1.Rewrite.response_headers_rewrite:type_name -> gateway.middleware.rewrite.v1.HeadersPolicy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_middleware_rewrite_v1_rewrite_proto_init() }
func file_gateway_middleware_rewrite_v1_rewrite_proto_init() {
	if File_gateway_middleware_rewrite_v1_rewrite_proto != nil {
		return
	}
	file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_rewrite_v1_rewrite_proto_rawDesc), len(file_gateway_middleware_rewrite_v1_rewrite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_rewrite_v1_rewrite_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_rewrite_v1_rewrite_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_rewrite_v1_rewrite_proto_msgTypes,
	}.Build()
	File_gateway_middleware_rewrite_v1_rewrite_proto = out.File
	file_gateway_middleware_rewrite_v1_rewrite_proto_goTypes = nil
	file_gateway_middleware_rewrite_v1_rewrite_proto_depIdxs = nil
}
