// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/middleware/cors/v1/cors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cors middleware config.
type Cors struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AllowCredentials    bool                   `protobuf:"varint,1,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	AllowOrigins        []string               `protobuf:"bytes,2,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowMethods        []string               `protobuf:"bytes,3,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	AllowHeaders        []string               `protobuf:"bytes,4,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	ExposeHeaders       []string               `protobuf:"bytes,5,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	MaxAge              *durationpb.Duration   `protobuf:"bytes,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	AllowPrivateNetwork bool                   `protobuf:"varint,7,opt,name=allow_private_network,json=allowPrivateNetwork,proto3" json:"allow_private_network,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Cors) Reset() {
	*x = Cors{}
	mi := &file_gateway_middleware_cors_v1_cors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cors) ProtoMessage() {}

func (x *Cors) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_cors_v1_cors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cors.ProtoReflect.Descriptor instead.
func (*Cors) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_cors_v1_cors_proto_rawDescGZIP(), []int{0}
}

func (x *Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Cors) GetExposeHeaders() []string {
	if x != nil {
		return x.ExposeHeaders
	}
	return nil
}

func (x *Cors) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

func (x *Cors) GetAllowPrivateNetwork() bool {
	if x != nil {
		return x.AllowPrivateNetwork
	}
	return false
}

var File_gateway_middleware_cors_v1_cors_proto protoreflect.FileDescriptor

const file_gateway_middleware_cors_v1_cors_proto_rawDesc = "" +
	"\n" +
	"%gateway/middleware/cors/v1/cors.proto\x12\x1agateway.middleware.cors.v1\x1a\x1egoogle/protobuf/duration.proto\"\xb1\x02\n" +
	"\x04Cors\x12+\n" +
	"\x11allow_credentials\x18\x01 \x01(\bR\x10allowCredentials\x12#\n" +
	"\rallow_origins\x18\x02 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x03 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x04 \x03(\tR\fallowHeaders\x12%\n" +
	"\x0eexpose_headers\x18\x05 \x03(\tR\rexposeHeaders\x122\n" +
	"\amax_age\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\x122\n" +
	"\x15allow_private_network\x18\a \x01(\bR\x13allowPrivateNetworkB=Z;github.com/go-kratos/gateway/api/gateway/middleware/cors/v1b\x06proto3"

var (
	file_gateway_middleware_cors_v1_cors_proto_rawDescOnce sync.Once
	file_gateway_middleware_cors_v1_cors_proto_rawDescData []byte
)

func file_gateway_middleware_cors_v1_cors_proto_rawDescGZIP() []byte {
	file_gateway_middleware_cors_v1_cors_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_cors_v1_cors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_cors_v1_cors_proto_rawDesc), len(file_gateway_middleware_cors_v1_cors_proto_rawDesc)))
	})
	return file_gateway_middleware_cors_v1_cors_proto_rawDescData
}

var file_gateway_middleware_cors_v1_cors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_middleware_cors_v1_cors_proto_goTypes = []any{
	(*Cors)(nil),                // 0: gateway.middleware.cors.v1.Cors
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_gateway_middleware_cors_v1_cors_proto_depIdxs = []int32{
	1, // 0: gateway.middleware.cors.v1.Cors.max_age:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_middleware_cors_v1_cors_proto_init() }
func file_gateway_middleware_cors_v1_cors_proto_init() {
	if File_gateway_middleware_cors_v1_cors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_cors_v1_cors_proto_rawDesc), len(file_gateway_middleware_cors_v1_cors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_cors_v1_cors_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_cors_v1_cors_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_cors_v1_cors_proto_msgTypes,
	}.Build()
	File_gateway_middleware_cors_v1_cors_proto = out.File
	file_gateway_middleware_cors_v1_cors_proto_goTypes = nil
	file_gateway_middleware_cors_v1_cors_proto_depIdxs = nil
}
